apiVersion: "dag.example.com/v1"
kind: Workflow
metadata:
  name: stress
spec:
  metadata:
    name: stress
  selector:
    matchLabels:
      workflow: stress
  steps:
  - name: "1.1"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_1
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "1.2"
    dependencies:
      - "1.1"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_1
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "1.3"
    dependencies:
      - "1.2"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_1
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "1.last"
    dependencies:
      - "1.3"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_1
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "2.1"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_2
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "2.2"
    dependencies:
      - "2.1"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_2
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "2.3"
    dependencies:
      - "2.2"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_2
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "2.last"
    dependencies:
      - "2.3"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_2
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "3.1"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_3
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "3.2"
    dependencies:
      - "3.1"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_3
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "3.3"
    dependencies:
      - "3.2"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_3
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "3.last"
    dependencies:
      - "3.3"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_3
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "4.1"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_4
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "4.2"
    dependencies:
      - "4.1"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_4
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "4.3"
    dependencies:
      - "4.2"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_4
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "4.last"
    dependencies:
      - "4.3"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_4
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "5.1"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_5
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "5.2"
    dependencies:
      - "5.1"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_5
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "5.3"
    dependencies:
      - "5.2"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_5
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "5.last"
    dependencies:
      - "5.3"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_5
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "6.1"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_6
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "6.2"
    dependencies:
      - "6.1"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_6
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "6.3"
    dependencies:
      - "6.2"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_6
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "6.last"
    dependencies:
      - "6.3"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_6
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "7.1"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_7
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "7.2"
    dependencies:
      - "7.1"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_7
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "7.3"
    dependencies:
      - "7.2"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_7
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "7.last"
    dependencies:
      - "7.3"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_7
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "8.1"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_8
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "8.2"
    dependencies:
      - "8.1"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_8
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "8.3"
    dependencies:
      - "8.2"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_8
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "8.last"
    dependencies:
      - "8.3"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_8
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "9.1"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_9
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "9.2"
    dependencies:
      - "9.1"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_9
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "9.3"
    dependencies:
      - "9.2"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_9
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "9.last"
    dependencies:
      - "9.3"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_9
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "10.1"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_10
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "10.2"
    dependencies:
      - "10.1"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_10
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "10.3"
    dependencies:
      - "10.2"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_10
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: "10.last"
    dependencies:
      - "10.3"
    jobTemplate:
      spec:
        template:
          metadata:
            name: stress_test_10_last
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-test
                image: alexeiled/stress-ng
                args : ["--parallel", "2", "--cpu", "8", "--hdd", "4", "--io", "4", "--timeout", "60s", "--metrics-brief"]
  - name: last
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              group: group_last
              workflow: stress
          spec:
            restartPolicy: OnFailure
            containers:
              - name: stress-end
                image: alpine
                command: ["sh", "-c", "echo Stress Test completed!"]
    dependencies:
      - 1.last
      - 2.last
      - 3.last
      - 4.last
      - 5.last
      - 6.last
      - 7.last
      - 8.last
      - 9.last
      - 10.last

